### ISSUE TITLE
No member named 'target' in 'es_event_create_t'

### ISSUE THREAD

**Issue by secretpray** [objective-see/FileMonitor#2]
File.m  (line 57)  //set path
            self.destinationPath = convertStringToken(&message->event.create.target->path);
Error -> No member named 'target' in 'es_event_create_t'

XCODE Version 11.0 (11A420a)
Mac OS: Mojave v10.14.6 (18G103)

**Comment by jemik** [comment]
as API has changed, you need to change
           ` self.destinationPath = convertStringToken(&message->event.create.target->path); `
to
        `     self.destinationPath = convertStringToken(&message->event.create.destination.new_path.filename);`

And do keep in mind, the Endpoint Security Framework, is only available in Mac OS 10.15.X.
[https://developer.apple.com/documentation/endpointsecurity?changes=latest_minor&language=objc](https://developer.apple.com/documentation/endpointsecurity?changes=latest_minor&language=objc)

**Comment by objective-see** [comment]
Thanks! Updated this locally - just checked in new code to reflect API changes
