### ISSUE TITLE
e2d73486... Doesn't build. Missing Base.lproj

### ISSUE THREAD

**Issue by gutley** [objective-see/FileMonitor#3]
I just tried building FileMonitor and Xcode is complaining it can't find FileMonitor/App/FileMonitor/Base.lproj.

i suspect it wasn't committed to git

**Comment by objective-see** [comment]
Ah thanks! 
Just updated the project to remove reference to this (unneeded file).

Note though, you'll have to update the code-signing info and add your own provisioning profile to get it to build cleanly (requirements leveraged by Apple, as the project uses the Endpoint Security Framework)
