### ISSUE TITLE
`extractSigningInfo` prints wrong cdHash

### ISSUE THREAD

**Issue by serges147** [objective-see/FileMonitor#5]
When there are bytes < 16 following code loses "0"-s :
```
    for(uint32_t i = 0; i<CS_CDHASH_LEN; i++)
    {
        //append
        [cdHash appendFormat:@"%X", process->cdhash[i]];
    }
```

**Comment by serges147** [comment]
I believe that formatting have to be `@"%02X"`.

**Comment by objective-see** [comment]
fixed! (in: https://github.com/objective-see/FileMonitor/commit/f0c5b1423e3657757aea208ede08b0ceb84d5d1c) 

Mahalo :)
